# Generated by Django 3.0.5 on 2020-04-09 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0004_auto_20200409_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 11, 31, 55, 188457, tzinfo=utc)),
        ),
    ]
